#!/usr/bin/expect

set port [lindex $argv 0]
spawn bash /root/ssr.sh

expect {
        "1-15"                  {send "7\r";         exp_continue}
        "(默认quit: 取消)"       {send "2\r";         exp_continue}
        "(默认: 取消):"          {send "$port\r";     exp_continue}
}

